In [1]:
def my_function():
    "This prints a string"
    print("Hello from a function")

In [2]:
my_function()

Hello from a function


In [4]:
def printme(nama): # parameter # nama holds value Triono / nama saya adalah ....
    "This prints a nama string into this function"
    print(nama)

In [5]:
printme("Triono") # argument

Triono


In [6]:
printme("nama saya adalah .....")

nama saya adalah .....


In [7]:
def printme(nama):
    "This prints a nama string into this function"
    print(nama)

In [8]:
printme() #tidak terdapat argument maka akan error missing required argument

TypeError: printme() missing 1 required positional argument: 'nama'

In [9]:
def printme(nama, alamat):
    "This prints a passed info into this function"
    print("Name: ", name)
    print("Age: ", age)
    return; # pengen nampilin apa di bagian paling akhir


In [10]:
printme("Triono", "Medan")

Triono
Medan


In [15]:
def printme(nama, alamat):
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [13]:
def printme(name, age):
    "This prints a passed info into this function"
    print("Name: ", name)
    print("Age: ", age)
    return; # pengen nampilin apa di bagian paling akhir


In [14]:
printme("Triono", "32")

Name:  Triono
Age:  32


In [19]:
def printme(nama = "Triono", alamat = "Medan"):
    "This prints a nama string into this function"
    print(nama)
    print(alamat)
    return

In [20]:
printme()

Triono
Medan


In [21]:
printme("Triono")

Triono
Medan


In [22]:
printme(alamat="Medan")

Triono
Medan


In [23]:
printme("Triono", "Medan")

Triono
Medan


# Variabel length argument
jika kita tidak tahu user akan memasukkan berapa argumen

In [27]:
def printinfo(arg1, *vartuple):
    "This prints a variable passed arguments"
    print("Output is: ")
    print(arg1)
    for var in vartuple:
        print(var)
    return;

In [28]:
printinfo(30)

Output is: 
30


In [29]:
printinfo(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

Output is: 
1
2
3
4
5
6
7
8
9
10


# Anonymous Function
Menggunakan lambda

In [30]:
sum = lambda arg1, arg2: arg1 + arg2;

In [31]:
sum (10, 20)

30

In [32]:
print ("Value of total:", sum (20, 20))

Value of total: 40


In [33]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total

In [35]:
sum(10, 20) # yang dihitung adalah total, sesuai dengan hasil yang diminta di return

30

In [36]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total1

In [38]:
sum (10, 20) # yang dihitung total, dilanjutkan ke total1

80

In [39]:
def sum(arg1, arg2):
    total = arg1 + arg2
    total1 = total + 50
    return total, total1

In [40]:
sum(10, 20) # menampilkan seperti yang diminta oleh return

(30, 80)

# Scope of variables
Global vs. Local Functions

In [44]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kelinci
    return tambahan

In [45]:
jumlahHewan()

50

In [47]:
tambahHewan() # error karena yang kelinci tidak didefinisikan di tambahHewan. Ini disebut lokal dan global function

NameError: name 'kelinci' is not defined

In [48]:
kucing = 20

def jumlahHewan():
    kelinci = 30
    hewan = kucing + kelinci
    return hewan

def tambahHewan():
    anjing = 20
    tambahan = anjing + kucing
    return tambahan

In [49]:
tambahHewan()

40

## Python Modules

In [50]:
import sys

In [51]:
sys.path

['C:\\Users\\tsyak',
 'C:\\Users\\tsyak\\anaconda3\\python37.zip',
 'C:\\Users\\tsyak\\anaconda3\\DLLs',
 'C:\\Users\\tsyak\\anaconda3\\lib',
 'C:\\Users\\tsyak\\anaconda3',
 '',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\tsyak\\.ipython']

In [52]:
sys.path.append(r'\Users\tsyak\desktop\h8package')

In [53]:
sys.path

['C:\\Users\\tsyak',
 'C:\\Users\\tsyak\\anaconda3\\python37.zip',
 'C:\\Users\\tsyak\\anaconda3\\DLLs',
 'C:\\Users\\tsyak\\anaconda3\\lib',
 'C:\\Users\\tsyak\\anaconda3',
 '',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\tsyak\\.ipython',
 '\\Users\\tsyak\\desktop\\h8package']

In [54]:
sys.path.append(r'C:\Users\tsyak\desktop\h8package')

In [55]:
sys.path

['C:\\Users\\tsyak',
 'C:\\Users\\tsyak\\anaconda3\\python37.zip',
 'C:\\Users\\tsyak\\anaconda3\\DLLs',
 'C:\\Users\\tsyak\\anaconda3\\lib',
 'C:\\Users\\tsyak\\anaconda3',
 '',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\win32\\lib',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\Pythonwin',
 'C:\\Users\\tsyak\\anaconda3\\lib\\site-packages\\IPython\\extensions',
 'C:\\Users\\tsyak\\.ipython',
 '\\Users\\tsyak\\desktop\\h8package',
 'C:\\Users\\tsyak\\desktop\\h8package']

In [56]:
import mod

In [62]:
mod.s # menampilkan yang ada di s (di mod.py)

'Hacktiv8 Inalum for Data Science'

In [63]:
mod.a # menampilkan yang ada di a (di mod.py)

[100, 200, 300]

In [64]:
mod.foo('Triono') # menampilkan yang ada di foo (di mod.py)

Triono


In [65]:
from mod import s, foo # import yang kita pilih (s dan foo)

In [66]:
s

'Hacktiv8 Inalum for Data Science'

In [67]:
foo('Triono')

Triono


In [68]:
from mod import s as string

In [69]:
string

'Hacktiv8 Inalum for Data Science'

In [70]:
import mod as my_module

In [71]:
my_module.a

[100, 200, 300]

In [72]:
my_module.s

'Hacktiv8 Inalum for Data Science'

In [74]:
sys.path.append(r'\Users\tsyak\desktop')

In [75]:
import H8package.mod

In [76]:
H8package.mod.s

'Hacktiv8 Inalum for Data Science'

In [77]:
!pip --version

pip 20.0.2 from C:\Users\tsyak\anaconda3\lib\site-packages\pip (python 3.7)



In [78]:
!pip install requests

In [79]:
import requests

## Numpy

In [80]:
import numpy as np

In [81]:
## Creating Array

a = np.array([1, 2, 3])

In [82]:
a

array([1, 2, 3])

In [83]:
np.zeros(5) # array 0 sebanyak 5

array([0., 0., 0., 0., 0.])

In [84]:
c = np.zeros(5)

In [85]:
print(c)

[0. 0. 0. 0. 0.]


In [86]:
d = np.ones(5)

In [87]:
print(d)

[1. 1. 1. 1. 1.]


In [90]:
np.arange(4) # np arange sebanyak 4 [dari 0 - 3]

array([0, 1, 2, 3])

In [92]:
np.arange(1, 10) # mulai dari 1 sebanyak 9 element (10 tidak masuk)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
np.arange(0, 20, 2) # start, stop, step

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [94]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [95]:
print(arr)

[1 2 3 4 5 6 7 8]


In [97]:
np.append(arr, [1, 2]) # add [array yang mau ditambah, penambahannya] --> penambahan di belakang

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2])

In [103]:
np.delete(arr, 1) 
# delete [array yang mau dihapus, posisi yang dihapus(2 merupakan posisi 1, sedang 1 merupakan posisi 0)] --> untuk yang ditambah tidak masuk karena tidak disimpan dalam variable arr

array([2, 5, 3, 7, 4, 6, 8])

In [104]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [105]:
print(arr)

[2 1 5 3 7 4 6 8]


In [106]:
np.sort(arr) # sorting

array([1, 2, 3, 4, 5, 6, 7, 8])

In [107]:
## Shape dan Size

In [113]:
array_example = np.array([
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]],
    [[0, 1, 2, 3],
     [4, 5, 6, 7]]
])

In [114]:
print(array_example)

[[[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]

 [[0 1 2 3]
  [4 5 6 7]]]


In [115]:
array_example.ndim # dimensi array

3

In [116]:
array_example.size # jumalh elemen --> misal ada 8

24

In [117]:
array_example.shape # bentuknya (berapa kebawah, berapa ke samping)

(3, 2, 4)

In [118]:
# Reshape

In [119]:
a = np.arange(6)

print(a)

[0 1 2 3 4 5]


In [121]:
b = a.reshape(3,2)

print(b)

[[0 1]
 [2 3]
 [4 5]]


In [122]:
a.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [123]:
a.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [124]:
# convert 1D to 2D

In [125]:
a

array([0, 1, 2, 3, 4, 5])

In [126]:
a.shape # 1D, 6 ke kanan

(6,)

In [127]:
a2 = a[np.newaxis]
print(a2)
print(a2.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [128]:
row_vector = a[np.newaxis, :]
print(row_vector)
print(row_vector.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [129]:
col_vector = a[:, np.newaxis]
print(col_vector)
print(col_vector.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [130]:
print(a)

[0 1 2 3 4 5]


In [131]:
print(a.shape)

(6,)


In [134]:
d = np.expand_dims(a, axis=1)
print(d)
print(d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]
(6, 1)


In [135]:
e = np.expand_dims(a, axis=0)
print(e)
print(e.shape)

[[0 1 2 3 4 5]]
(1, 6)


In [136]:
## indexing dan slicing

In [138]:
data = np.array([1, 2, 3])

In [140]:
data[0] # data ke0

1

In [141]:
data[1] # data ke1

2

In [142]:
data[2] # data ke2

3

In [143]:
data[0:2]

array([1, 2])

In [146]:
data[1:]

array([2, 3])

In [147]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [148]:
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [149]:
a[a<8]

array([1, 2, 3, 4, 5, 6, 7])

In [150]:
a[a>=8]

array([ 8,  9, 10, 11, 12])

In [151]:
lebih_lima = (a >= 5)

a[lebih_lima]

array([ 5,  6,  7,  8,  9, 10, 11, 12])

In [152]:
a[(a > 2) & (a < 11)]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [153]:
# Create array from existing data

In [154]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])

In [156]:
arr1 = arr[3 : 9]
print(arr1)

[4 5 6 7 8 9]


In [157]:
a_1 = np.array([[1,1],
               [2,2]])
print(a_1)

[[1 1]
 [2 2]]


In [158]:
a_2 = np.array([[3,3],
               [4,4]])
print(a_2)

[[3 3]
 [4 4]]


In [159]:
np.vstack((a_1, a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [160]:
np.hstack((a_1, a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [161]:
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [162]:
np.hsplit(arr, 5)

[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8]), array([ 9, 10])]

In [163]:
# view dan copy

In [164]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [165]:
b = a.view() # hanya view dari a --> jika a diubah maka b akan berubah
print(b)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [166]:
c = a.copy() # copy dari a --> jika a diubah maka c akan tetap
print(c)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [167]:
# basic array operations

In [168]:
a_1

array([[1, 1],
       [2, 2]])

In [169]:
a_2

array([[3, 3],
       [4, 4]])

In [170]:
a_2 - a_1 # dengan numpy bisa langsung dioperasi tambah, kurang kali, maupun bagi

array([[2, 2],
       [2, 2]])

In [171]:
a_2 / a_1

array([[3., 3.],
       [2., 2.]])

In [173]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [174]:
arr.sum()

55

In [175]:
a_1

array([[1, 1],
       [2, 2]])

In [176]:
a_1.sum()

6

In [177]:
a_1.sum(axis=0) # menjumlahkan ke bawah

array([3, 3])

In [178]:
a_1.sum(axis=1) # menjumlahkan ke samping

array([2, 4])

In [179]:
a_1 * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [180]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [181]:
a.sum()

78

In [184]:
print(a.min())

print(a.max())

1
12


In [185]:
a.min(axis=0) # paling atas

array([1, 2, 3, 4])

In [186]:
a.min(axis=1) # paling kiri

array([1, 5, 9])

In [187]:
a.max(axis=0) # paling bawah

array([ 9, 10, 11, 12])

In [188]:
a.max(axis=1) # paling kanan

array([ 4,  8, 12])

In [189]:
np.array([[1,2], [3,4]])

array([[1, 2],
       [3, 4]])

In [190]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [191]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [192]:
np.random.random((3,2))

array([[0.97290713, 0.88072052],
       [0.02823568, 0.99996983],
       [0.13100054, 0.7446275 ]])

In [193]:
# Matrix Arithmetic

In [194]:
data = np. array([[1,2], [3,4]])
print(data)

[[1 2]
 [3 4]]


In [195]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [196]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [197]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [198]:
data + ones_row # numpy akan menambahkan 2 elemen dibawahnya

array([[2., 3.],
       [4., 5.]])

In [199]:
a_1 = np.array([[1,2,3], [4,5,6]])
print(a_1)

a_2 = np.array([[7,8], [9,10], [11,12]])
print(a_2)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


In [200]:
print(a_1.shape)
print(a_2.shape)

(2, 3)
(3, 2)


In [201]:
np.dot(a_1, a_2)

array([[ 58,  64],
       [139, 154]])

In [203]:
data = np.array([[1,2], [3,4], [5,6]])

print(data)

[[1 2]
 [3 4]
 [5 6]]


In [204]:
data[0,1]

2

In [205]:
data[1,1]

4

In [206]:
data[1:3]

array([[3, 4],
       [5, 6]])

In [207]:
data[0:2]

array([[1, 2],
       [3, 4]])

In [208]:
data[0:2, 0]

array([1, 3])

In [211]:
print(data.max())

print(data.min())

print(data.sum())

6
1
21


In [212]:
data.max(axis=1)

array([2, 4, 6])

In [213]:
data.max(axis=0)

array([5, 6])

In [214]:
# Transposing dan Reshaping

In [215]:
data

array([[1, 2],
       [3, 4],
       [5, 6]])

In [216]:
data.T

array([[1, 3, 5],
       [2, 4, 6]])

In [217]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [218]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [219]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [220]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


In [221]:
# ND Array

In [222]:
ndarr = np.array([[[1,2], [3,4]],
                 [[5,6], [7,8]]])

ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [223]:
np.ones((4,3,2))

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [225]:
np.zeros((4,3,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [226]:
np.random.random((4,3,2))

array([[[0.89590216, 0.93053804],
        [0.34964587, 0.67707916],
        [0.48473592, 0.41753443]],

       [[0.14207047, 0.19917498],
        [0.50331781, 0.52093346],
        [0.89587284, 0.66968333]],

       [[0.39861668, 0.17977748],
        [0.60699386, 0.65201205],
        [0.12040727, 0.00235442]],

       [[0.93798941, 0.26987299],
        [0.26941177, 0.79651466],
        [0.66374574, 0.72912732]]])

In [227]:
# Flatten

In [228]:
ndarr.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8])

In [230]:
a = np.random.random(5)

print(a)

a.shape #rank 1 Array

[0.53847218 0.12466322 0.95302012 0.00978542 0.35488822]


(5,)

In [231]:
a.T

array([0.53847218, 0.12466322, 0.95302012, 0.00978542, 0.35488822])

In [232]:
np.dot(a, a.T)

1.3397819590244184

In [236]:
a = np.random.rand(5, 1) #column vector

print(a)

[[0.39089258]
 [0.47793755]
 [0.27376776]
 [0.10893086]
 [0.50056419]]


In [238]:
print(a.shape)

print(a.T)

(5, 1)
[[0.39089258 0.47793755 0.27376776 0.10893086 0.50056419]]


In [239]:
a = np.random.rand(1, 5)

In [240]:
a.shape

(1, 5)

In [241]:
a

array([[0.53621874, 0.69183658, 0.77012624, 0.64428313, 0.19194652]])

In [242]:
ndarr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [243]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [244]:
ndarr = np.array([[[1,2], [3,4]], [[5,6], [7,8]]])

In [245]:
ndarr

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])